-- Run once on existing PostgreSQL DBs (adds referral columns L6–L10 only).
-- For DBs that might miss L1–L5 too, use instead: postgres-migration-users-referral-l1-l10.sql
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_count_l6 INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_count_l7 INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_count_l8 INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_count_l9 INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_count_l10 INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_earnings_l6 TEXT NOT NULL DEFAULT '0';
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_earnings_l7 TEXT NOT NULL DEFAULT '0';
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_earnings_l8 TEXT NOT NULL DEFAULT '0';
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_earnings_l9 TEXT NOT NULL DEFAULT '0';
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_earnings_l10 TEXT NOT NULL DEFAULT '0';
