-- Run once on RDS if `users` is missing referral columns (full L1–L10 counts + earnings).
-- Safe to re-run: IF NOT EXISTS per column.
-- Matches: backend/scripts/postgres-schema.sql

-- Per-level referral counts (L1 … L10)
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_count_l1 INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_count_l2 INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_count_l3 INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_count_l4 INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_count_l5 INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_count_l6 INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_count_l7 INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_count_l8 INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_count_l9 INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_count_l10 INTEGER NOT NULL DEFAULT 0;

ALTER TABLE users ADD COLUMN IF NOT EXISTS total_referrals INTEGER NOT NULL DEFAULT 0;

-- Per-level referral earnings (wei strings, L1 … L10) + total
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_earnings_l1 TEXT NOT NULL DEFAULT '0';
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_earnings_l2 TEXT NOT NULL DEFAULT '0';
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_earnings_l3 TEXT NOT NULL DEFAULT '0';
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_earnings_l4 TEXT NOT NULL DEFAULT '0';
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_earnings_l5 TEXT NOT NULL DEFAULT '0';
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_earnings_l6 TEXT NOT NULL DEFAULT '0';
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_earnings_l7 TEXT NOT NULL DEFAULT '0';
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_earnings_l8 TEXT NOT NULL DEFAULT '0';
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_earnings_l9 TEXT NOT NULL DEFAULT '0';
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_earnings_l10 TEXT NOT NULL DEFAULT '0';
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_earnings_total TEXT NOT NULL DEFAULT '0';
